import java.net.URI

/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.6.1/userguide/multi_project_builds.html
 */

rootProject.name = "imagej"


includeBuild("core")
includeBuild("common")

//dependencyResolutionManagement {
//    repositories {
//        mavenCentral()
//        maven("https://maven.scijava.org/content/groups/public")
//    }
//}
//
//sourceControl {
//    gitRepository(URI("https://github.com/imagej/imagej.git")) {
//        producesModule("net.imagej:imagej")
//    }
//}
//


//dependencyResolutionManagement {
//    versionCatalogs {
//        //        create("libs") {
//        //            from(files("gradle/dependencies.toml"))
//        //        }
//        create("batik") { from(files("gradle/batik.toml")) }
//        create("bonej") { from(files("gradle/bonej.toml")) }
//        create("fiji") { from(files("gradle/fiji.toml")) }
//        create("groovy") { from(files("gradle/groovy.toml")) }
//        create("imagej") { from(files("gradle/imagej.toml")) }
//        //        File("$rootDir/gradle").listFiles()?.map {
//        //        if (it.name != "wrapper")
//        //            create(it.nameWithoutExtension) {
//        //                from(files("gradle/${it.name}"))
//        //            }
//        //       }
//    }
//}

